# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'

- task: DotNetCoreCLI@2
  displayName: 'Install dotnet-ef'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global dotnet-ef'


- task: DotNetCoreCLI@2
  displayName: Generate SQL migration scripts
  inputs:
    command: custom
    workingDirectory: '$(Build.SourcesDirectory)/Source/PWManagerServiceModelEF/PWManagerServiceModelEF.csproj'
    custom: 'ef '
    arguments: migrations script -o $(Build.ArtifactStagingDirectory)/migrations/scripts.sql --context DataContext -v -i

#- task: SqlAzureDacpacDeployment@1
#  displayName: Apply SQL migrations
#  inputs:
#    azureSubscription: '2891e653-8679-4f90-9105-59c14c5ce1c2'
#    AuthenticationType: 'server'
#    ServerName: 'isefpwmanagerdbserver.database.windows.net'
#    DatabaseName: 'ISEFPWManagerDB'
#    SqlUsername: 'isefsa'
#    SqlPassword: '5^#YA8VdGobZKC92eAgVsxJXJf2ZZL8i%y@2r&s2^B%7x3sHC@bVDdPWDyrxF@85ryWEfXs48ABy*i^tgEx53F8ytU$#LZPu$svTjQ3@bB&qVAEofC9RpSzzD7tRMyMK'
#    deployType: 'SqlTask'
#    SqlFile: '$(Pipeline.Workspace)/drop/migrations/scripts.sql'
#    IpDetectionMethod: 'AutoDetect'

- task: SqlAzureDacpacDeployment@1
  inputs:
    AuthenticationType: 'aadAuthenticationIntegrated'
    ServerName: 'isef01-pw-manager-sql-server.database.windows.net'
    DatabaseName: 'isef01-pw-manager-sql-db'
    deployType: 'SqlTask'
    SqlFile: '$(Pipeline.Workspace)/drop/migrations/scripts.sql'
    IpDetectionMethod: 'AutoDetect'
#- task: UseDotNet@2
#  inputs:
#    packageType: 'sdk'
#    version: '7.x'

#- task: efcore-migration-script-generator-task@1
#  inputs:
#    projectpath: '$(Build.SourcesDirectory)/Source/PWManagerServiceModelEF/PWManagerServiceModelEF.csproj'
#    databasecontexts: 'dataContext'
#    startupprojectpath: '$(Build.SourcesDirectory)/Source/PWManagerService/PWManagerService.csproj'
#    targetfolder: '$(build.artifactstagingdirectory)/migrations'
#    build: false
    #installdependencies: true
    
